### ISSUE TITLE
Remove "User (you):" under Livepeer Token balance

### ISSUE THREAD

**Issue by chrishobcroft** [videoDAC/livepeer-aragon#10]
Currently, the Delegator tab shows the user the Livepeer Token balance of their own address e.g. controlled with their own MetaMask.

This is confusing to a user as when they are interacting with this DAO, they would primarily be managing the DAO's funds.

Propose to remove this altogether.

**Comment by chrishobcroft** [comment]
Closing as it is covered off in https://github.com/videoDAC/livepeer-aragon/issues/12

**Comment by willjgriff** [comment]
Don't you think this would be useful in the account tab where a user has the option of depositing LPT?

**Comment by chrishobcroft** [comment]
I would remove it, as it really blurs the lines between what is the user's money and what is the DAO's money. The only time I see my money referenced in Aragon is when I have already specifically requested to Deposit money into the Finance app - and that's only after I've selected the token that I want to put in.
