### ISSUE TITLE
Transcoder function - vote shows Reward Cut / Fee Share / Price Per Segment as 10x actual values

### ISSUE THREAD

**Issue by chrishobcroft** [videoDAC/livepeer-aragon#11]
### Current situation

When a vote is proposed to call `transcoder`, the values shown in the vote are 10x the actual values proposed, and also 10x the values sent to the smart contract call.

### Proposed solution

Re-jig the math's to make sure that the vote displays the correct numbers being proposed for the Transcoder configuration.

### Screenshots

Configure the parameters for the `transcoder` function:

![image](https://user-images.githubusercontent.com/2212651/57776300-08606900-7717-11e9-963d-290494222d7f.png)

See how the system will communicate the choices:

![image](https://user-images.githubusercontent.com/2212651/57776342-1c0bcf80-7717-11e9-9595-512138f909ce.png)

View the vote:

![image](https://user-images.githubusercontent.com/2212651/57776365-29c15500-7717-11e9-8cb9-f78601545d4b.png)

**Comment by willjgriff** [comment]
Fixed at some previous commit.

**Comment by chrishobcroft** [comment]
Confirmed as fixed on Rinkeby.

Closing
