### ISSUE TITLE
Proposal for new UI Layout

### ISSUE THREAD

**Issue by chrishobcroft** [videoDAC/livepeer-aragon#12]
### Delegator Tab

![1  Livepeer App - Delegator](https://user-images.githubusercontent.com/2212651/57872788-64ed8200-7804-11e9-9407-3f925df3559c.png)

Notes:
- The link at the bottom should up the STAKING tab of the App's page in explorer.livepeer.org

### Transcoder Tab

![2  Livepeer App - Transcoder](https://user-images.githubusercontent.com/2212651/57872789-64ed8200-7804-11e9-8a16-b8a55e49ea36.png)

Notes:
- The link at the bottom should up the TRANSCODING tab of the App's page in explorer.livepeer.org

### Account Tab

![3  Livepeer App - Account](https://user-images.githubusercontent.com/2212651/57872790-65861880-7804-11e9-8751-2b9fb20c3330.png)

Notes:
- The link at the bottom should up the OVERVIEW tab of the App's page in explorer.livepeer.org

### Settings Tab

![4  Livepeer App - Settings](https://user-images.githubusercontent.com/2212651/57872791-65861880-7804-11e9-9e10-df50e76d1c62.png)

**Comment by chrishobcroft** [comment]
Also see the proposal for the new App Icon: https://github.com/videoDAC/livepeer-aragon/issues/14

**Comment by pythonpete32** [comment]
This new layout is much cleaner and less confusing. Removing the livepeer token address and getting rid of your personal LPT is definitely the way to go. 

There still a navigation issue, all the other apps have a hamburger menu when viewing on mobile to take you back to the other apps ![hamburger](https://imgshare.io/image/screenshot-20190521-193152.rkYk4) and ![no hamburger]https://imgshare.io/image/rkqpY)

**Comment by willjgriff** [comment]
Completed UI update as of commit: 04e45f4a40cd781b52a5b811e9de2e52fb99fb2e

Added hamburger as of commit: 13c5df219e1f39d3f8d676f0d98b93a18c24ffd9

**Comment by chrishobcroft** [comment]
Bravo - it all looks really good.
