### ISSUE TITLE
Delegated amount shows 0 if App has not Declared Transcoder

### ISSUE THREAD

**Issue by chrishobcroft** [videoDAC/livepeer-aragon#13]
### Current Behaviour

If the App has attracted some stake, but has not called `transcoder`, the Delegated amount is shown as `0` in the UI.

### Expected behaviour

If an App has attracted some Delegated stake, it should show in the app UI.

### Screenshots

![image](https://user-images.githubusercontent.com/2212651/57944493-18bb4400-78cf-11e9-9bde-058359b1ddf3.png)

### Other notes

This is likely an extreme edge-case, so probably very low priority to fix.

**Comment by willjgriff** [comment]
I titled it incorrectly. This value is actually the transcoders total stake, which is different from delegated amount. Delegated amount refers to the amount an address has delegated. Total stake is the amount delegated to this address. It is 0 until declared as a transcoder.

**Comment by willjgriff** [comment]
I've renamed 'Delegated Amount' to 'Total Stake' to hopefully avoid confusion.

**Comment by chrishobcroft** [comment]
Unfortunately, I expect that the term 'Total Stake' might create more confusion.

To clarify, within Livepeer's protocol, _any Ethereum address_ can have the following two parameters associated with it:

**STAKE**: this is the amount of stake that has been delegated **_from this address_**.

**DELEGATED AMOUNT**: this is the amount of stake that has been delegated **_to this address_**.

Both of these can be non-zero _**even if the address has not declared as a Transcoder**_ - see screenshot below from Livepeer Explorer (on Rinkeby).

So I would propose that the amount shown in the TRANSCODER tab of the Livepeer Aragon app should be labelled "DELEGATED AMOUNT" (as per the Explorer), and which ought to mirror the information displayed in the explorer, even before the app has declared `transcoder` (which is currently not the case, as per the original post).

![Screenshot from 2019-05-23 10-06-06](https://user-images.githubusercontent.com/2212651/58240274-96a1a400-7d42-11e9-8094-f035bdd28ff7.png)

**Comment by willjgriff** [comment]
Fixed as of commit: 25690b4df910570e4a33a0004906d8094fc66559

**Comment by chrishobcroft** [comment]
Validated as fixed on Rinkeby.
