### ISSUE TITLE
No hamburger button on mobile view

### ISSUE THREAD

**Issue by pythonpete32** [videoDAC/livepeer-aragon#15]
When interacting with Aragon apps on mobile, the app bar on the left is not displayed. Other Aragon apps have a hamburger to get back to the previous apps

**Comment by chrishobcroft** [comment]
Yeah, this seems like it ought to be there.

@pythonpete32 please can you include some screenshots of what you're seeing - for example, comparing the Livepeer App page (without hamburger button) with e.g. the Voting app page (with hamburger button).

**Comment by willjgriff** [comment]
Fixed as of commit: 13c5df219e1f39d3f8d676f0d98b93a18c24ffd9

**Comment by chrishobcroft** [comment]
Validated on Google Pixel 2 XL

Closing
