### ISSUE TITLE
Empower app to Rebond

### ISSUE THREAD

**Issue by chrishobcroft** [videoDAC/livepeer-aragon#6]
When a delegator has unbonded tokens from the network (created an unbonding lock), and is waiting for the unbonding period to elapse, it has the opportunity to _rebond_ the tokens which have been unbonded as part of the unbonding lock. This has the effect of rebonding them to the network.

This change request is to develop the functionality to rebond tokens to the network during the unbonding period for a specific unbonding lock.

**Comment by willjgriff** [comment]
Completed in commit: b9ef06319086698d8252b98f23afa87a591b281c
